#!/bin/sh
# Deploy the application to the Internet.
set -e
git push origin master
ssh proseline.com <<'SCRIPT'
set -e
if [ ! -d proseline ]; then
  git clone https://github.com/proseline/proseline proseline
fi
cd proseline
old_hash="$(shasum package-lock.json)"
git fetch origin
git reset --hard origin/master
new_hash="$(shasum package-lock.json)"
if [ "$old_hash" != "$new_hash" ]; then
  npm ci --production
fi
systemctl --user restart proseline
SCRIPT
